"""initial schema

Revision ID: f71a69a631f7
Revises: 
Create Date: 2026-06-25 20:58:20.630735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71a69a631f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_username'), 'audit_log', ['actor_username'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('group_no', sa.Integer(), nullable=True),
    sa.Column('number_in_group', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('water_source', sa.String(), nullable=True),
    sa.Column('commission_year', sa.Integer(), nullable=True),
    sa.Column('capacity_m3s', sa.Float(), nullable=True),
    sa.Column('length_before_km', sa.Float(), nullable=True),
    sa.Column('length_before_earth_km', sa.Float(), nullable=True),
    sa.Column('length_before_lined_km', sa.Float(), nullable=True),
    sa.Column('length_after_km', sa.Float(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('kpd_design', sa.Float(), nullable=True),
    sa.Column('kpd_actual', sa.Float(), nullable=True),
    sa.Column('district_raw', sa.String(), nullable=True),
    sa.Column('rural_okrug_raw', sa.String(), nullable=True),
    sa.Column('wear_percent', sa.Float(), nullable=True),
    sa.Column('condition_source', sa.String(), nullable=True),
    sa.Column('cadastre_number', sa.String(), nullable=True),
    sa.Column('gosakt_number', sa.String(), nullable=True),
    sa.Column('significance', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('needs_reconstruction', sa.Boolean(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('anchor_key', sa.String(), nullable=True),
    sa.Column('anchor_name', sa.String(), nullable=True),
    sa.Column('coords_approximate', sa.Boolean(), nullable=True),
    sa.Column('last_inspection_date', sa.Date(), nullable=True),
    sa.Column('next_inspection_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('is_user_created', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_code'), 'objects', ['code'], unique=True)
    op.create_index(op.f('ix_objects_id'), 'objects', ['id'], unique=False)
    op.create_index(op.f('ix_objects_object_type'), 'objects', ['object_type'], unique=False)
    op.create_index(op.f('ix_objects_status'), 'objects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('changed_by_username', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_id'), 'status_history', ['id'], unique=False)
    op.create_index(op.f('ix_status_history_object_id'), 'status_history', ['object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_object_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_objects_status'), table_name='objects')
    op.drop_index(op.f('ix_objects_object_type'), table_name='objects')
    op.drop_index(op.f('ix_objects_id'), table_name='objects')
    op.drop_index(op.f('ix_objects_code'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_username'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
